### ISSUE TITLE
rewrite committee duty stopping mechanism

### ISSUE THREAD

**Issue by moshe-blox** [ssvlabs/ssv#1572]
https://github.com/ssvlabs/ssv/blob/c433b1b9c9909c950578f598d540fd70de09c420/protocol/v2/ssv/validator/committee.go#L210-L218

Few issues with today's mechanism:
- We duplicate roughly the same `stoppedValidators` map in every runner, and there are likely race conditions because of no locks in the runners
- We don't really stop attester duties when newer ones start

I suggest that we should keep track of stopped duties in the parent (`Committee`), albeit differently. Committee should contain a map of public keys to highest attester slot, and pass the runners a function to check if an attester duty is still valid or not.
- Refactor `StartDuty` to populate the map with the pubkeys and slots (only for attester duties where the slot is higher)
- Remove `StopDuty` and refactor `stopValidator` to just delete the pubkey from the map
- Add `validAttesterDuty` method which checks that the pubkey exists and the slot is lower or equal, and pass this method to the runners to replace their `stoppedValidators` map
- Optimize the runner to stop itself if no duty is valid to save resources
- ~~Question: since sync committee duties are unsubmittable past their slot, should we also consider those invalid inside the runners? this would enable us to save even more resources with the self-stopping optimization, when sync committee duties are stuck on change round~~

**Comment by MatheusFranco99** [comment]
We don't have this functionality in spec anymore.
For SSV, I agree that managing the stopped validators should be the responsibility of `Committee` and not `CommitteeRunner` (and I agree with the proposed change).

**Comment by moshe-blox** [comment]
> We don't have this functionality in spec anymore. For SSV, I agree that managing the stopped validators should be the responsibility of `Committee` and not `CommitteeRunner` (and I agree with the proposed change).

What do you think about stopping sync committee duties once their slot has passed?
Now that I'm thinking about it again it doesn't sound like a very significant optimization, because it would only benefit committees which are stuck on change round with sync duties and a small validator set (otherwise you cant stop most runners because of still valid attestations)

**Comment by MatheusFranco99** [comment]
> What do you think about stopping sync committee duties once their slot has passed, in order to be able to later stop "empty" runners? (where all duties are deemed invalid)
Now that I'm thinking about it again it doesn't sound like a very significant optimization, because it would only benefit committees which are stuck on change round with sync duties and a small validator set (otherwise you cant stop most runners because of still valid attestations in most slots)

I agree, seems unlikely so not much gain from the optimization. But, I would say that it's still a valid feature, so could be added if not too costly.
