### ISSUE TITLE
add DutyScheduler forking tests for all handlers

### ISSUE THREAD

**Issue by moshe-blox** [ssvlabs/ssv#1607]
After issue https://github.com/ssvlabs/ssv/issues/1604 is resolved, we should make sure there's at least one test for all handlers that would check ExecuteGenesisDuty is called at pre-fork and that it would switch to ExecuteDuty at post-fork ideally both with and without recreating the handler.

This should undo PR https://github.com/ssvlabs/ssv/pull/1606 fixes the ProposerHandler test after which is a temporary fix for the ProposerHandler tests, because that PR makes the tests blind to which execution function was called.

**Comment by y0sher** [comment]
Especially for genesis (for example proposer)
