### ISSUE TITLE
drop peers with low score or irrelevant subnets

### ISSUE THREAD

**Issue by moshe-blox** [ssvlabs/ssv#1662]
On the fork epoch, operator nodes unsubscribe from subnets which are no longer relevant. This means some of the connections made before the fork might become irrelevant, if we no longer share subnets with them.

Beacon nodes running few validators very often change their subnets, so they should a similar same problem.

We should look into how Beacon clients handle this issue before deciding how to go about it for SSV.

### Proposal
We can call `PubSub.ListPeers(topic)` periodically for each topic we're subscribed to and with it populate a map of peer IDs to their subscribed topics, and finally use this map to disconnect from peers with 0 shared subnets, and potentially also in AppSpecificScore to rank each peer according to how many subnets they share with us.

**Comment by MatheusFranco99** [comment]
With a second read, it seems that **indeed GossipSub doesn't disconnect the bad peers**. Basically, it only drops the peer if it's dead or blacklisted.

**Prysm** prunes peers by using a [forever loop in which it checks if there are any bad peers and disconnects if so](https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/sync/rpc_status.go#L29-L52) ([sendGoodbyeAndDisconnect function](https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/sync/rpc_goodbye.go#L55-L94), [disconnect function](https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/p2p/service.go#L338-L341)). It also has a ["sanity" like prune method](https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/p2p/peers/status.go#L580-L636).

An **issue** is that **GossipSub must be alerted** of this peer removal to safely store the peer's score (in case it reconnects later). I'll check how this can be ensured.

Regarding 0-shared subnets, I think GossipSub naturally keeps track of "fanout" topics and "fanout" peers. This means that there could be two forces indefinitely pushing each other. But, definitely, we can drop some in case we are full or near full.

Regarding app-specific score, again this may impact these "fanout" peers who may join later on and I'm concerned with unpredictable behaviours this may produce. I would stick with the disconnection for now.
