### ISSUE TITLE
Missing duty limit validation for SYNC_COMMITTEE_CONTRIBUTION

### ISSUE THREAD

**Issue by olegshmuelov** [ssvlabs/ssv#1753]
It appears that there's no duty limit validation for the `SYNC_COMMITTEE_CONTRIBUTION` role in the `dutyLimit` function:
```go
func (mv *messageValidator) dutyLimit(msgID spectypes.MessageID, slot phase0.Slot, validatorIndexCount int) (int, bool) {
    switch msgID.GetRoleType() {
    case spectypes.RoleVoluntaryExit:
        pk := phase0.BLSPubKey{}
        copy(pk[:], msgID.GetDutyExecutorID())
        return mv.dutyStore.VoluntaryExit.GetDutyCount(slot, pk), true

    case spectypes.RoleAggregator, spectypes.RoleValidatorRegistration:
        return 2, true

    case spectypes.RoleCommittee:
        return 2 * validatorIndexCount, true

    default:
        return 0, false
    }
}
```
Currently, `SYNC_COMMITTEE_CONTRIBUTION` is not covered, which could result in unvalidated limits for this role

**Comment by MatheusFranco99** [comment]
The `dutyLimit` function should not be called for the `SYNC_COMMITTEE_CONTRIBUTION` and `PROPOSER` duties. For such duties, we actually check if the duty exists or not using the duty fetcher (instead of posing a limit per epoch)
